LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := com.huawei.audioalgo
LOCAL_MODULE_OWNER := honor
LOCAL_SRC_FILES := system/framework/com.huawei.audioalgo.jar
LOCAL_MODULE_SUFFIX := $(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_DEX_PREOPT := false
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hwEmui
LOCAL_MODULE_OWNER := honor
LOCAL_SRC_FILES := system/framework/hwEmui.jar
LOCAL_MODULE_SUFFIX := $(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_DEX_PREOPT := false
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hwpostcamera
LOCAL_MODULE_OWNER := honor
LOCAL_SRC_FILES := system/framework/hwpostcamera.jar
LOCAL_MODULE_SUFFIX := $(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_DEX_PREOPT := false
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)
